### PR TITLE
Made a VF for Google Fonts

### PR DESCRIPTION
**Pull request by RosaWagner**
Hi,
I made a variable font for you. While I was inspecting the sources, I found some stuff which are a bit inconvenient.

1. Absence of set v-metrics. I added them as I think you wanted, but please check them, and consider that, if possible, centred uppercases would be a nice thought to developers.
2. ExtraLight and ExtraBold was missing, but I don't think there were enough space to add them, so instead I reduced the range (Thin -> ExtraLight, Black -> ExtraBold). This is to anticipate the problem of instanciation of a variable font from the API. 
3. Designspace was not orthogonal. Your master "regular" was having 400 as coordinates, and your instance "regular" was at "380". Therefore I created a new master from this instance. Please consider removing the former regular instance (called regular2) after checking that the new one is Okay.

Now about these nested components… you didn't have to decompose all outlines. You could have just decompose the comb accents, and they wouldn't have been nested in the accented letters. But in any case `gftools builder` "flatten" them automatically during export, and Fontmake has flag to do so. I set up a config.yaml file to be able to use gftools builder, and instruction in your README.md to replicate the process. It is indeed required by our spec to build the fonts with our tools.

Please consider re-build the accented letters with components, it is important to preserve file size and so fast web pages.

### CODE REVIEW

**Comment by yellow-type-foundry** [comment]
@RosaWagner I see that you added a custom parameter which is "Axis mappings" without changing the export values. So do we need to change those values or just the parameter will do?

**Comment by RosaWagner** [comment]
I am sorry, I don't what you mean. The axis mapping is linking the instances' coordinates to the user values (usWeightClass), so we are sure that the location you chose is the one exported (but with the proper usWeightClass). I checked, and the axis mapping is correct. In any case, it only affects the variable font, and you only want to ship statics. Am I answering your question?

**Comment by bettergui** [comment]
I got a question: regarding "...., but I don't think there were enough space to add them, so instead I reduced the range.... This is to anticipate the problem of instanciation of a variable font from the API._".
Can you tell us more about why there weren't enough space? Is it still an issue now when we have two separate source files for regular and italic?

FYI, we have added the missing ExtraLight and ExtraBold instances to have the full 18 static files in the PR: https://github.com/google/fonts/pull/3456

**Comment by RosaWagner** [comment]
It depends on point on views, you can add intermediate instances or reduce the range. The why if each options is too long to explain by writing and I am in holidays :) just make sure you have the same values and same instances in the Roman and the Italic, with correct user values, and correct coordinates in the axis mapping and exports settings, so everything is consistent with your choice :)

**Comment by bettergui** [comment]
Understood now. Thank you for taking the time to reply while in holidays and for all the advices.

**Pull request merged**
